[package]
name = "lufact"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Sparse LU factorization with partial pivoting"
repository = "https://github.com/rwl/lufact_rs"

[dependencies]
lufact-sys = "0.2"
log = "0.4"
env_logger = "0.10"
